---
output:
  pdf_document: default
  html_document: default
---
# Conclusions {#conclusions}

This manual has highlighted the history, context, rationale, and approaches for using spatial analysis tools and area based social metrics (ABSMs) to describe, analyze, visualize and communicate health inequities across geographic levels.

The case studies serve as opportunities to apply the topics highlighted in the manual to specific datasets and research questions. During the workshops held in the Summer of 2022, participants worked through the case studies using the following [presentation template](https://docs.google.com/presentation/d/1sZR8j9pizPJHfPcD84KCOGxVz9WVeEqRZP_-GaX5nR8/edit?usp=sharing). 

This template offers a systematic way to work through key questions in carrying out spatial analyses using ABSMs while applying a health equity lens. We highlight the key questions and elements of this template below to serve as a guide when developing research projects and studies of this nature. We hope that this may be of use in your current and future work!

## Key questions to ask

- State the study objective include:
    a. *Population*
    b. *Timeframe*
    c. *Why this is of interest?*
    d. *Whom do you want to do what, with whom, to use the knowledge generated by your study to advance health justice?*
    
- What are the key health equity concerns?

- What ABSMs are most relevant to your objective?
    a. *Whom is it in reference to (numerator/denominator)?*
    b. *What is the data source?*
    c. *What are key concerns?*
    
- What geographic level is used? Why?

- What is the analytic approach?
    a. *What is your outcome of interest*
    b. *How are you characterizing the relationships between your health outcome of interest and the ABSM of interest? (e.g. risk ratio? Risk difference? Rate difference? Rate ratio?)*
    c. *Are you doing age adjustment and if so how?*
    d. *Are you using a regression model? If so, please specify?*
    e. *Are you going to model spatial effects? (e.g. Multilevel or spatial modeling approach)*

- What are key findings?
    a. *Present exploratory (univariate) tables, figures and/or maps that help contextualize your results*
    b. *Present regression models if relevant*
    c. *Summarize association between ABSMs and the health outcome*
    d. *Comment on the effect of age adjustment*
    e. *Present maps and visualizations*