

## Data Governance

There is only so much data users can do to account for poor data or the absence of data. Therefore, improvements in the availability and quality of health data and, in particular, improvements to the use of social metrics in conceptualizing and analyzing this data, are necessary. **Data governance** is therefore a critical feature of addressing health disparities. Data governance is about "who has input into making the decisions about which data are required, informed by the tandem expertise of health equity researchers and other members of the communities whose data are at stake, affording the expertise of lived experience" (Krieger, 2021). See [*Structural Racism, Health Inequities, and the Two-Edged Sword of Data: Structural Problems Require Structural Solutions*](https://www.frontiersin.org/articles/10.3389/fpubh.2021.655447/full) for a proposed "two-part institutional mandate regarding the reporting and analysis of publicly-funded work involving racialized groups and health data and documentation as to why the proposed mandates are feasible" (Krieger, 2021).

Part of demanding improved data governance is interrogating the sources of data currently available, including their sampling strategies, underlying theories that inform their design, and who is involved in their generation - in line with ecosocial theory's construct of accountability and agency. By exploring the origins of one's data (both the actual records and the history of the data systems and categories at issue) and the processes through which they have been generated, data analysts and proponents of health justice can better articulate the potential for bias in the data, identify means of improving data collection to mitigate this bias, and actively call for structural change in data collection and governance. 

Another key component of equity-oriented data governance is to make data openly accessible, with relevant safeguards for data privacy and use, so as to enable communities to ask their own data-driven questions, and not just rely on what analyses get published by governmental agencies or academic researchers. This also requires more robust infrastructure for community science, transparent review of methods and findings, and strengthened capacity for community-oriented knowledge translation to enhance agency. Although it is beyond the scope of our technical PHDGP 2.0 training to provide guidance on the specifics of equity-oriented data governance for the particular projects in which diverse groups are engaged, issues of data governance, sovereignty, and privacy are increasingly the focus of critical analysis and practice (Else 2022, Carroll, Rodriguez-Lonebear and Martinez 2019, Committee on National Statistics 2019, US Census Bureau 2020, Krieger et al. 2020).
