
## References

Krieger N. The US Census and the People's Health: Public Health Engagement From Enslavement and "Indians Not Taxed" to Census Tracts and Health Equity (1790-2018). Am J Public Health. 2019 Aug;109(8):1092-1100. doi: 10.2105/AJPH.2019.305017. Epub 2019 Jun 20.

Nethery, Rachel C., Tamara Rushovich, Emily Peterson, Jarvis T. Chen, Pamela D. Waterman, Nancy Krieger, Lance Waller, and Brent A. Coull. "Comparing denominator sources for real-time disease incidence modeling: American Community Survey and WorldPop." SSM-Population Health 14 (2021): 100786.

Rothman, Kenneth J., Sander Greenland, and Timothy L. Lash. Modern Epidemiology. Vol. 3. Philadelphia: Wolters Kluwer Health/Lippincott Williams & Wilkins, 2008.

Else H. African researchers lead campaign for equity in global collaborations. Nature. 2022 Jun 10. doi: 10.1038/d41586-022-01604-3. Epub ahead of print.

Carroll SR, Rodriguez-Lonebear D, Martinez A. Indigenous Data Governance: Strategies from United States Native Nations. Data Sci J. 2019;18:31. doi: 10.5334/dsj-2019-031.

Committee on National Statistics. The National Academies of Sciences, Engineering, and Medicine. Workshop on 2020 Census Data Products: Data Needs and Privacy Considerations. Washington, DC: December 11–12, 2019. Available at: https://sites.nationalacademies.org/DBASSE/CNSTAT/DBASSE_196518. Accessed June 14, 2022.

US Census Bureau. Understanding differential privacy. https://www.census.gov/programs-surveys/decennial-census/decade/2020/planning-management/process/disclosure-avoidance/differential-privacy.html ; accessed June 14, 2022.

Krieger N, Nethery RC, Chen JT, Waterman PD, Wright E, Rushovich T, Coull BA. Impact of Differential Privacy and Census Tract Data Source (Decennial Census Versus American Community Survey) for Monitoring Health Inequities. Am J Public Health. 2021 Feb;111(2):265-268. doi: 10.2105/AJPH.2020.305989. Epub 2020 Dec 22.